#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


# Down the last running theme:
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# Set the theme.toml config:
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"


xdg-user-dirs-update

# Disable screen saver blanking:
xset s off

# Set background:
if [ -x "$(command -v feh)" ]; then
  feh --randomize --bg-fill --no-fehbg /etc/nixos/assets/wallpapers/bing/*
fi


index=0
monitors="$(polybar -m | sed s/:.*//)"
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  let indextemp=index+1
  monitor=$(sed "$indextemp!d" <<<"$monitors")
  barname="mainbar$index"
  monitor=$monitor offset=$x width=$width polybar -c $SCRIPTPATH/polybar.config $barname &> /dev/null &
  let index=indextemp
done


lxqt-policykit-agent &
lxqt-notificationd &
pcmanfm-qt --daemon-mode --desktop-off &

nm-tray &
pasystray &
