{ config, pkgs, lib, ... }:

{
  # Enable lightdm-tiny-greeter as the lightdm greeter.
  # Note that this greeter starts only the default X session. You can configure the default X session using `services.xserver.displayManager.defaultSession`.
  services.xserver.displayManager.lightdm.greeters.tiny.enable = lib.mkForce true;

  services.xserver.displayManager.lightdm.greeters.tiny.label = {
    user = "User"; # the string to represent the user_text label
    pass = "Pass"; # the string to represent the pass_text label
  };

  # Section to describe style and ui:
  services.xserver.displayManager.lightdm.greeters.tiny.extraConfig = ''
    /* GTK UI CSS */
    static const gchar *style =
    "window {"
        "background-color: #EEEEEE;"
    "}"
    "window * {"
        "font: 16px \"Roboto\";"
    "}"
    "label {"
        "color: #005F87;"
        "margin-right: 15px;"
        "font-weight: bold;"
    "}"
    "entry {"
        "color: #444444;"
        "background-color: #FCFCFC;"
        "box-shadow: none;"
    "}"
    "#message_label {"
        "color: #D70087;"
        "margin-top: 25px;"
        "font-size: 16px;"
    "}";
    /* GTK UI XML*/
    static const gchar *ui =
    "<?xml version='1.0' encoding='UTF-8'?>"
    "<interface>"
      "<requires lib='gtk+' version='3.20'/>"
      "<object class='GtkWindow' id='login_window'>"
        "<property name='name'>login_window</property>"
        "<property name='can_focus'>False</property>"
        "<property name='resizable'>False</property>"
        "<property name='accept_focus'>False</property>"
        "<property name='decorated'>False</property>"
        "<child>"
          "<placeholder/>"
        "</child>"
        "<child>"
          "<object class='GtkBox' id='login_box'>"
            "<property name='name'>login_box</property>"
            "<property name='visible'>True</property>"
            "<property name='can_focus'>False</property>"
            "<property name='valign'>center</property>"
            "<property name='vexpand'>True</property>"
            "<property name='orientation'>vertical</property>"
            "<child>"
              "<object class='GtkBox' id='prompt_box'>"
                "<property name='name'>prompt_box</property>"
                "<property name='visible'>True</property>"
                "<property name='can_focus'>False</property>"
                "<property name='spacing'>15</property>"
                "<property name='homogeneous'>True</property>"
                "<child>"
                  "<object class='GtkLabel' id='prompt_label'>"
                    "<property name='name'>prompt_label</property>"
                    "<property name='visible'>True</property>"
                    "<property name='can_focus'>False</property>"
                    "<property name='halign'>end</property>"
                  "</object>"
                  "<packing>"
                    "<property name='expand'>False</property>"
                    "<property name='fill'>True</property>"
                    "<property name='position'>0</property>"
                  "</packing>"
                "</child>"
                "<child>"
                  "<object class='GtkEntry' id='prompt_entry'>"
                    "<property name='name'>prompt_entry</property>"
                    "<property name='visible'>True</property>"
                    "<property name='can_focus'>True</property>"
                    "<property name='halign'>start</property>"
                    "<property name='has_frame'>False</property>"
                    "<property name='max_width_chars'>15</property>"
                    "<property name='primary_icon_activatable'>False</property>"
                    "<property name='secondary_icon_activatable'>False</property>"
                    "<signal name='activate' handler='login_cb' swapped='no'/>"
                  "</object>"
                  "<packing>"
                    "<property name='expand'>False</property>"
                    "<property name='fill'>True</property>"
                    "<property name='position'>1</property>"
                  "</packing>"
                "</child>"
              "</object>"
              "<packing>"
                "<property name='expand'>False</property>"
                "<property name='fill'>True</property>"
                "<property name='position'>0</property>"
              "</packing>"
            "</child>"
            "<child>"
              "<object class='GtkLabel' id='message_label'>"
                "<property name='name'>message_label</property>"
                "<property name='visible'>True</property>"
                "<property name='can_focus'>False</property>"
                "<property name='halign'>center</property>"
                "<property name='width_chars'>25</property>"
                "<property name='max_width_chars'>50</property>"
              "</object>"
              "<packing>"
                "<property name='expand'>False</property>"
                "<property name='fill'>True</property>"
                "<property name='position'>1</property>"
              "</packing>"
            "</child>"
          "</object>"
        "</child>"
      "</object>"
    "</interface>";
  '';
}
