#!/usr/bin/env bash

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

ld-export-xdg-user-vars
xdg-user-dirs-update


# Down the last running theme:
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# Set the theme.toml config:
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"


# Disable screen saver blanking:
xset s off

# Set background:
if [ -x "$(command -v feh)" ]; then
  feh --randomize --bg-fill --no-fehbg /etc/nixos/assets/wallpapers/bing/*
fi


lxqt-policykit-agent &
lxqt-notificationd &


index=0
monitors="$(polybar -m | sed s/:.*//)"
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  let indextemp=index+1
  monitor=$(sed "$indextemp!d" <<<"$monitors")
  barname="mainbar$index"
  monitor=$monitor offset=$x width=$width polybar -c $SCRIPTPATH/polybar.config $barname &> /dev/null &
  let index=indextemp
done


#nm-tray &
#pasystray &

#pkill polybar
#echo "---" | tee -a ~/.cache/polybar-mainbar0.log
#polybar -c $SCRIPTPATH/polybar.config mainbar0 >>~/.cache/polybar-mainbar0.log 2>&1 &
